"use client";

import Link from "next/link";
import Image from "next/image";
import QRCode from "qrcode";
import { useEffect, useState } from "react";
import { cn, formatCurrency } from "@/lib/utils";

type Status = "Draft" | "Sent" | "Viewed" | "Pending" | "Paid" | "Cancelled";
type Bill = { number: string; customer: string; phone: string; amount: number; status: Status; date: string };
export const bills: Bill[] = [
  { number: "QB-0001", customer: "Aarav Mehta", phone: "+91 98765 43210", amount: 12500, status: "Pending", date: "Today, 10:42 AM" },
  { number: "QB-0002", customer: "Priya Sharma", phone: "+91 99112 33221", amount: 8600, status: "Paid", date: "Today, 9:15 AM" },
  { number: "QB-0003", customer: "Nikhil Jain", phone: "+91 98100 11552", amount: 4200, status: "Viewed", date: "Yesterday" },
  { number: "QB-0004", customer: "Riya Kapoor", phone: "+91 98999 22331", amount: 18000, status: "Sent", date: "23 Jul 2026" },
];

const billLink = "https://quickbill.onelink.cards/bill/QB-0001";

export function QuickBillLogo({ className = "" }: { className?: string }) {
  return <Image src="/quickbill-logo.png" alt="QuickBill — Scan. View. Pay." width={550} height={190} priority className={cn("object-contain", className)} />;
}

function Icon({ name, className }: { name: string; className?: string }) {
  const paths: Record<string, React.ReactNode> = {
    plus: <path d="M12 5v14M5 12h14" />, arrow: <path d="M5 12h14m-6-6 6 6-6 6" />, copy: <><rect x="8" y="8" width="11" height="11" rx="2" /><path d="M5 16H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v1" /></>, share: <><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><path d="m8.6 10.5 6.8-4m0 11-6.8-4" /></>, check: <path d="m5 12 4 4L19 6" />, download: <path d="M12 3v12m-5-5 5 5 5-5M5 21h14" />, more: <path d="M12 5.5v.01M12 12v.01M12 18.5v.01" strokeWidth="3" />, search: <><circle cx="11" cy="11" r="6" /><path d="m16 16 4 4" /></>, phone: <path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1.9.3 1.7.6 2.5a2 2 0 0 1-.5 2.1L8 9.5a16 16 0 0 0 6 6l1.2-1.2a2 2 0 0 1 2.1-.5c.8.3 1.6.5 2.5.6a2 2 0 0 1 1.7 2.5Z" />, receipt: <><path d="M5 3h14v18l-3-2-4 2-4-2-3 2V3Z" /><path d="M8 8h8M8 12h8" /></>, calendar: <><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M16 3v4M8 3v4M3 10h18" /></>, user: <><circle cx="12" cy="8" r="4" /><path d="M4 21a8 8 0 0 1 16 0" /></>, message: <path d="M21 11.5a8.4 8.4 0 0 1-9 8.4 9.4 9.4 0 0 1-4.1-1L3 20l1.3-4.5A8.4 8.4 0 0 1 12.5 3 8.5 8.5 0 0 1 21 11.5Z" />,
  };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={cn("h-5 w-5", className)} aria-hidden>{paths[name]}</svg>;
}

export function StatusBadge({ status }: { status: Status }) {
  const styles: Record<Status, string> = { Draft: "bg-slate-100 text-slate-600", Sent: "bg-sky-50 text-sky-600", Viewed: "bg-violet-50 text-violet-600", Pending: "bg-amber-50 text-amber-700", Paid: "bg-emerald-50 text-emerald-700", Cancelled: "bg-rose-50 text-rose-600" };
  return <span className={cn("inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold", styles[status])}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>;
}

export function QuickBillShell({ children, active = "Overview" }: { children: React.ReactNode; active?: string }) {
  const nav = [{ name: "Overview", href: "/quickbill" }, { name: "Bills", href: "/quickbill" }, { name: "Customers", href: "/quickbill" }];
  return <div className="min-h-screen bg-[#f8fafc] text-[#0f172a]"><header className="sticky top-0 z-20 border-b border-[#e4eee2] bg-white/85 px-4 py-2.5 backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Link href="/quickbill" className="flex items-center"><QuickBillLogo className="h-5 w-[72px]" /></Link><nav className="hidden items-center gap-1 md:flex">{nav.map((item) => <Link key={item.name} href={item.href} className={cn("rounded-lg px-3.5 py-2 text-sm font-semibold", active === item.name ? "bg-[#edf8ec] text-[#378a2e]" : "text-slate-500 hover:bg-slate-50")}>{item.name}</Link>)}</nav><div className="flex items-center gap-3"><span className="hidden text-right text-xs font-semibold text-slate-500 sm:block">Kriyon Group<br /><span className="font-medium text-slate-400">Business workspace</span></span><div className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-[#6fbd45] to-[#277b2d] text-xs font-bold text-white">KG</div></div></div></header>{children}</div>;
}

export function StatCard({ label, value, detail, tone = "sky" }: { label: string; value: string; detail: string; tone?: "sky" | "green" | "amber" | "violet" }) {
  const icon = tone === "green" ? "check" : tone === "amber" ? "receipt" : tone === "violet" ? "calendar" : "arrow";
  const bg = { sky: "bg-sky-50 text-sky-600", green: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", violet: "bg-violet-50 text-violet-600" }[tone];
  return <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_18px_35px_-28px_rgba(15,23,42,.45)]"><div className="flex items-start justify-between"><p className="text-sm font-semibold text-slate-500">{label}</p><span className={cn("grid h-9 w-9 place-items-center rounded-xl", bg)}><Icon name={icon} className="h-4 w-4" /></span></div><p className="mt-4 text-2xl font-extrabold tracking-[-.04em]">{value}</p><p className="mt-1 text-xs font-medium text-slate-400">{detail}</p></div>;
}

export function BillCard({ bill }: { bill: Bill }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-extrabold">{bill.customer}</p><p className="mt-0.5 text-xs font-medium text-slate-400">{bill.number} · {bill.date}</p></div><StatusBadge status={bill.status} /></div><div className="mt-4 flex items-end justify-between border-t border-slate-100 pt-3"><p className="text-lg font-extrabold">{formatCurrency(bill.amount)}</p><Link href="/quickbill/bill/QB-0001" className="text-xs font-bold text-sky-600">View bill</Link></div></div>; }

export function BillTable() { return <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left"><thead className="border-b border-slate-100 text-[11px] font-bold uppercase tracking-[.08em] text-slate-400"><tr><th className="px-5 py-4">Bill no.</th><th className="px-4 py-4">Customer</th><th className="px-4 py-4">Phone</th><th className="px-4 py-4">Amount</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Date</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{bills.map((bill) => <tr key={bill.number} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4 text-sm font-bold text-sky-600">{bill.number}</td><td className="px-4 py-4 text-sm font-bold">{bill.customer}</td><td className="px-4 py-4 text-sm font-medium text-slate-500">{bill.phone}</td><td className="px-4 py-4 text-sm font-extrabold">{formatCurrency(bill.amount)}</td><td className="px-4 py-4"><StatusBadge status={bill.status} /></td><td className="px-4 py-4 text-xs font-medium text-slate-500">{bill.date}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link href="/quickbill/bill/QB-0001" className="rounded-lg border border-slate-200 p-2 text-slate-500 hover:text-sky-600"><Icon name="receipt" className="h-4 w-4" /></Link><button className="rounded-lg border border-slate-200 p-2 text-slate-500 hover:text-sky-600"><Icon name="share" className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{bills.map((bill) => <BillCard key={bill.number} bill={bill} />)}</div></>; }

export function QRCard({ compact = false, payment = false }: { compact?: boolean; payment?: boolean }) {
  const [code, setCode] = useState("");
  const value = payment ? "upi://pay?pa=kriyongroup@upi&pn=Kriyon%20Group&am=12500&cu=INR&tn=QuickBill%20QB-0001" : billLink;
  useEffect(() => { QRCode.toDataURL(value, { width: 560, margin: 1, color: { dark: "#17350f", light: "#ffffff" } }).then(setCode); }, [value]);
  return <div className={cn("rounded-3xl border border-[#dcebd8] bg-white text-center shadow-[0_20px_44px_-30px_rgba(44,105,38,.25)]", compact ? "p-4" : "p-6")}><div className={cn("mx-auto rounded-2xl border border-[#dcebd8] bg-white p-3", compact ? "max-w-[150px]" : "max-w-[245px]")}><div className="relative aspect-square overflow-hidden rounded-lg bg-[#f3faef]">{code ? <Image src={code} alt={payment ? "UPI payment QR code" : "Bill QR code"} fill unoptimized className="object-contain" /> : <div className="h-full w-full animate-pulse bg-[#e6f5e1]" />}</div></div><p className="mt-4 text-sm font-extrabold text-[#1c3b16]">{payment ? "Scan to pay ₹12,500" : "Scan to view your bill"}</p><p className="mt-1 text-xs font-medium text-slate-400">{payment ? "UPI payment to Kriyon Group" : "Secure QuickBill link"}</p></div>;
}

export function ShareActions() { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard?.writeText(billLink); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }; return <div className="grid gap-2 sm:grid-cols-2"><button onClick={copy} className="qb-secondary"><Icon name={copied ? "check" : "copy"} className="h-4 w-4" />{copied ? "Bill link copied" : "Copy bill link"}</button><a href={`https://wa.me/?text=${encodeURIComponent(`Hi Aarav, your bill from Kriyon Group is ready. View it here: ${billLink}`)}`} target="_blank" rel="noreferrer" className="qb-secondary text-[#378a2e]"><Icon name="message" className="h-4 w-4" />Send on WhatsApp</a></div>; }

export function BillPreview({ slim = false }: { slim?: boolean }) { const items = [{ name: "Brand identity consultation", quantity: 1, rate: 8500 }, { name: "Website audit report", quantity: 1, rate: 4000 }]; return <div className={cn("rounded-2xl border border-slate-200 bg-white shadow-[0_22px_45px_-32px_rgba(15,23,42,.35)]", slim ? "p-5" : "p-6 sm:p-8")}><div className="flex justify-between border-b border-slate-100 pb-5"><div><p className="text-lg font-extrabold tracking-[-.03em]">Kriyon Group</p><p className="mt-1 text-xs font-medium text-slate-400">QuickBill by OneLink</p></div><div className="text-right"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Bill no.</p><p className="mt-1 text-sm font-extrabold text-sky-600">QB-0001</p></div></div><div className="grid gap-4 py-5 text-sm sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Bill to</p><p className="mt-1 font-bold">Aarav Mehta</p><p className="text-xs text-slate-500">+91 98765 43210</p></div><div className="sm:text-right"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Issued on</p><p className="mt-1 font-bold">26 July 2026</p><p className="text-xs text-slate-500">Due 02 August 2026</p></div></div><div className="overflow-hidden rounded-xl border border-slate-100"><div className="grid grid-cols-[1fr_40px_72px] gap-2 bg-slate-50 px-3 py-2.5 text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:grid-cols-[1fr_60px_90px_90px]"><span>Item</span><span className="hidden sm:block">Qty</span><span className="hidden sm:block">Rate</span><span className="text-right">Amount</span></div>{items.map((item) => <div key={item.name} className="grid grid-cols-[1fr_40px_72px] gap-2 border-t border-slate-100 px-3 py-3 text-sm sm:grid-cols-[1fr_60px_90px_90px]"><span className="font-semibold">{item.name}</span><span className="hidden text-slate-500 sm:block">{item.quantity}</span><span className="hidden text-slate-500 sm:block">{formatCurrency(item.rate)}</span><span className="text-right font-bold">{formatCurrency(item.rate)}</span></div>)}</div><div className="ml-auto mt-5 max-w-[250px] space-y-2 text-sm"><div className="flex justify-between text-slate-500"><span>Subtotal</span><span>{formatCurrency(12500)}</span></div><div className="flex justify-between text-slate-500"><span>Discount</span><span>₹0</span></div><div className="flex justify-between border-t border-slate-100 pt-3 text-base font-extrabold"><span>Total amount</span><span>{formatCurrency(12500)}</span></div></div><div className="mt-6 border-t border-slate-100 pt-4 text-center text-[11px] font-medium text-slate-400">Generated via QuickBill by OneLink</div></div>; }
